timwong00/GC-Final-Project-Escape-Room

src/app/app.module.ts
src/app/room1left/room1left.component.html
src/app/room1left/room1left.component.spec.ts
src/app/room1left/room1left.component.ts
src/app/room1right/room1right.component.html
src/app/room1right/room1right.component.spec.ts
src/app/room1right/room1right.component.ts
src/app/room2front/room2front.component.html
src/app/room2front/room2front.component.spec.ts
src/app/room2front/room2front.component.ts
src/app/room2left/room2left.component.html
src/app/room2left/room2left.component.spec.ts
src/app/room2left/room2left.component.ts
src/app/room2right/room2right.component.html
src/app/room2right/room2right.component.spec.ts
src/app/room2right/room2right.component.ts
src/app/room3front/room3front.component.html
src/app/room3front/room3front.component.spec.ts
src/app/room3front/room3front.component.ts
src/app/room3left/room3left.component.html
src/app/room3left/room3left.component.spec.ts
src/app/room3left/room3left.component.ts
src/app/room3right/room3right.component.html
src/app/room3right/room3right.component.spec.ts
src/app/room3right/room3right.component.ts

created the rest of the room components and their paths.

created rest of room components and paths

---

src/app/app.component.html
src/app/room1.service.ts
src/app/room1front/room1front.component.ts
src/app/room2.service.ts
src/app/tutorialroom.service.spec.ts
src/app/tutorialroom.service.ts
src/styles.css

Fixed services and added tutorial component. Tested if items worked in browser.

Fix services

---

connection.js
package.json
src/app/soundeffect.service.spec.ts
src/app/soundeffect.service.ts

soundeffect service getting sound links from API

got sound effect links from API

---

src/app/soundeffect.service.ts

added sound effects

---

src/app/room-navigation/room-navigation.component.css
src/app/room-navigation/room-navigation.component.html

Arrows for navigation is now visible

Show arrow pics

---

src/app/app.component.css
src/app/app.component.html
src/app/room1front/room1front.component.html
src/app/room1left/room1left.component.html
src/app/room2front/room2front.component.html
src/app/room2front/room2front.component.ts
src/app/room3front/room3front.component.html
src/app/room3front/room3front.component.ts
src/app/tutorialfront/tutorialfront.component.html

just need win/lose game messages

messages created for each stage

---

src/app/match.service.ts
src/app/room-navigation/room-navigation.component.html
src/app/room-navigation/room-navigation.component.ts
src/app/tutorialroom.service.ts

removed click arrow to use getGameProgress function
instead when the arrow is clicked; it will check game Progress

fixed navigation bug

---

src/app/header/header.component.css
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/match.service.ts
src/app/room1.service.ts
src/app/room1front/room1front.component.ts
src/app/room1left/room1left.component.ts
src/app/room1right/room1right.component.ts
src/app/timer.service.ts
src/app/tutorialfront/tutorialfront.component.ts
src/app/tutorialroom.service.ts

Synced battery animation timer with timer will start after tutorial is finished

Sync timer battery

---

src/app/room1.service.ts
src/app/room1front/room1front.component.ts
src/app/room1left/room1left.component.ts
src/app/room1right/room1right.component.ts
src/app/tutorialfront/tutorialfront.component.ts
src/app/tutorialroom.service.ts

tutorial room front and room 1 component won't subscribe unless the service item and unlockitems  is undefined

fixed room 1 win condition not working

---

src/app/header/header.component.css
src/app/tutorialright/tutorialright.component.css
src/app/tutorialright/tutorialright.component.html

positioned key on table + changed inventory item to white text

positioned key on table + changed inventory item to white text

---

connection.js
src/app/room1front/room1front.component.css
src/app/room1front/room1front.component.html
src/app/room1left/room1left.component.css
src/app/room1left/room1left.component.html
src/app/room1right/room1right.component.css
src/app/room1right/room1right.component.html
src/app/tutorialright/tutorialright.component.html

Finished setting up room 1 views

completed room 1 views

---

src/app/app.module.ts
src/app/end-game/end-game.component.css
src/app/end-game/end-game.component.html
src/app/end-game/end-game.component.spec.ts
src/app/end-game/end-game.component.ts
src/app/header/header.component.ts
src/app/match.service.ts
src/app/room1.service.ts
src/app/room1front/room1front.component.ts
src/app/timer.service.ts
src/app/tutorialroom.service.ts

end component shows if user wins

---

src/app/room-navigation/room-navigation.component.ts

added so that keydown WASD works

changed the room nav so it will navigate with arrows or WASD

---

src/app/header/header.component.css
src/app/header/header.component.html
src/app/room-navigation/room-navigation.component.css
src/app/room1.service.ts
src/app/room2.service.ts
src/app/room3.service.ts
src/app/tutorialfront/tutorialfront.component.css
src/app/tutorialfront/tutorialfront.component.html
src/app/tutorialleft/tutorialleft.component.css
src/app/tutorialleft/tutorialleft.component.html
src/app/tutorialright/tutorialright.component.css
src/app/tutorialright/tutorialright.component.html
src/app/tutorialroom.service.ts
src/styles.css

only tutorial rooms front/left/right mobile portrait and landscape is done
need to complete tablet and desktop as well as positioning items

Style tut rooms

---

src/app/header/header.component.html
src/app/header/header.component.ts

got cursor to work with hard-coded image.

image will show as cursor when clicked

---

src/app/app.component.ts
src/app/game-progression.service.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/match.service.ts
src/app/timer.service.ts

worked on timer and added playing game status

---

src/app/header/header.component.css
src/app/header/header.component.html
src/app/header/header.component.ts

made it so you can click on and off of inventory items

added on and off option to inventory items for click function

---

src/app/app.component.ts
src/app/header/header.component.css
src/app/header/header.component.html
src/app/match.service.ts
src/app/room-navigation/room-navigation.component.ts
src/app/room3right/room3right.component.css
src/app/soundeffect.service.ts
src/app/timer.service.ts

Heartbeat will play when timer is getting low and will increase in volume as time gets lower
Timer will now display as minutes and seconds

Sync heartbeat

---

src/app/header/header.component.css
src/app/header/header.component.html

styled header and added logo image and altered menu to "quit game" button

header component styling

---

src/app/tutorialright/tutorialright.component.html
src/app/tutorialright/tutorialright.component.ts
src/app/tutorialroom.service.ts

and won't reappear when switching components

flashlight will hide when clicked 

---

src/app/match.service.ts
src/app/room1.service.ts
src/app/room1left/room1left.component.ts
src/app/room2.service.ts
src/app/room2right/room2right.component.ts
src/app/room3.service.ts
src/app/room3right/room3right.component.ts
src/app/soundeffect.service.ts
src/app/tutorialright/tutorialright.component.ts
src/app/tutorialroom.service.ts

Added cut door handle sound
added key code sound

Add more sound
